name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Expose secrets
      run: |
        echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        echo "${{ secrets.AWS_REGION }}"